### ISSUE TITLE
 GroundItems.getNearest causes nullpointers

### ISSUE THREAD

**Issue by danihodovic** [Parabot/Parabot-377-API-Minified#2]
java.lang.NullPointerException
at org.rev377.min.api.methods.GroundItems.getGroundItemsAt(GroundItems.java:80)
at org.rev377.min.api.methods.GroundItems.getGroundItems(GroundItems.java:53)
at org.rev377.min.api.methods.GroundItems.getNearest(GroundItems.java:119)
at org.rev377.min.api.methods.GroundItems.getNearest(GroundItems.java:140)
at org.script.Loot.activate(Loot.java:36)
at org.parabot.environment.scripts.framework.StrategyWorker.execute(Frameworks.java:55)
at org.parabot.environment.scripts.Script.run(Script.java:106)
at java.lang.Thread.run(Thread.java:745)

The stacktrace above. After this, it logs 

java.lang.NullPointerException

a million times before exiting the client. The error occurred in a Battlescape script.

**Comment by JKetelaar** [comment]
Could you provide some more information? Script information etcetera.

**Comment by danihodovic** [comment]
Fixed this issue, it had to do with the client logging itself out if no activity ocurred. Java's robot class is a hack fix.
